# database and common
USER = "user"
ID = "id"
NAME = "name"
PASSWORD = "password"
NEW_NAME = "new_name"
BITS = "bits"
SC_SERVER_URL = "sc_server_url"
SC_CREATE_USER_ENDPOINT = "sc_create_user_endpoint"
SC_CREATE_USER_URL = "sc_create_user_url"
AUTH_SERVER = "auth_server"
WS_JSON_URL = "ws_json_url"
PROTOCOL = "protocol"
HOST = "host"
PORT = "port"
GET_TOKENS_ENDPOINT = "get_tokens_endpoint"
GET_ACCESS_TOKEN_ENDPOINT = "get_access_toke_endpoint"
USER_ENDPOINT = "user_endpoint"
USERS_ENDPOINT = "users_endpoint"

# messages
MSG_ACCESS_DENIED = "msg_access_denied"
MSG_INVALID_REQUEST = "msg_invalid_request"
# MSG_ALL_DONE = "msg_all_done"
# MSG_INVALID_USERNAME = "msg_invalid_username"
# MSG_INVALID_PASSWORD = "msg_invalid_password"
# MSG_USER_NOT_FOUND = "msg_user_not_found"
# MSG_USER_IS_IN_BASE = "msg_user_is_in_base"
# MSG_SC_SERVER_ERROR = "msg_sc_server_error"
# MSG_SC_SERVER_NO_CONNECTION = "msg_sc_server_no_connection"
MSG_CODE = "msg_code"
# MSG_CODES = "msg_codes"
MSG_TEXT = "msg_text"

# token properties and keys
ISS = "iss"
EXP = "exp"
EXPIRES_IN = "expires_in"
TOKEN_TYPE = "token_type"
JWT = "JWT"
TOKEN = "token"
ACCESS_TOKEN = "access_token"
ACCESS_TOKEN_LIFE_SPAN = "access_token_life_span"
REFRESH_TOKEN = "refresh_token"
REFRESH_TOKEN_LIFE_SPAN = "refresh_token_life_span"
ISSUER = "issuer"
USERNAME = "username"
TOKEN_QUERY_ARG = "token_query_arg"

# for new user generation
RREL_1 = "rrel_1"
RREL_2 = "rrel_2"
TEMPLATE = "template"
ARGS = "args"
LOGIN = "login"
VALUE = "value"
TYPE = "type"
ROLE = "role"
NODE = "node"
EDGE = "edge"
FILE = "file"
MAIN = "main"
LINK = "link"
